/**
 * Unified wrapper pipeline for cross-cutting concerns around functional interfaces.
 *
 * <p>This package provides a decorator-based pipeline that wraps standard Java functional
 * interfaces ({@link java.lang.Runnable}, {@link java.util.function.Supplier},
 * {@link java.util.concurrent.Callable}, {@link java.util.function.Function}) and
 * AOP proxy executions ({@link eu.inqudium.core.pipeline.function.JoinPointExecutor}) in a chain
 * of layers with <strong>around-semantics</strong>.</p>
 *
 * <h2>Architecture Overview</h2>
 *
 * <p>The architecture is layered into two levels:</p>
 *
 * <ol>
 *   <li><strong>{@link eu.inqudium.core.pipeline.LayerAction}</strong> — the fundamental
 *       around-advice contract. A functional interface that receives chain ID, call ID,
 *       argument, and a reference to the next step. It decides when, whether, and how
 *       to invoke the next step. All other abstractions build on this.</li>
 *
 *   <li><strong>{@link eu.inqudium.core.pipeline.InqDecorator}</strong> — extends
 *       {@code LayerAction} and {@link eu.inqudium.core.element.InqElement} with
 *       {@code decorateXxx()} factory methods that create reusable wrapper objects for
 *       deferred execution. The decorator carries both metadata (name, type, events) and
 *       behavior (the around-advice), making it the standard building block for
 *       resilience elements like bulkheads, retries, and circuit breakers.</li>
 * </ol>
 *
 * <h2>Wrapper Chain Infrastructure</h2>
 *
 * <p>The chain infrastructure is built on:</p>
 * <ul>
 *   <li>{@link eu.inqudium.core.pipeline.AbstractBaseWrapper} — holds the immutable chain
 *       structure: delegate, name, chain ID, and shared call-ID counter.</li>
 *   <li>{@link eu.inqudium.core.pipeline.BaseWrapper} — adds synchronous execution by
 *       wiring the next-step reference and the {@code LayerAction} at construction time.</li>
 *   <li>Concrete wrappers: {@link eu.inqudium.core.pipeline.function.RunnableWrapper},
 *       {@link eu.inqudium.core.pipeline.function.SupplierWrapper},
 *       {@link eu.inqudium.core.pipeline.function.CallableWrapper},
 *       {@link eu.inqudium.core.pipeline.function.FunctionWrapper},
 *       {@link eu.inqudium.core.pipeline.function.JoinPointWrapper} — each implements its
 *       respective functional interface and is a drop-in replacement for the delegate.</li>
 * </ul>
 *
 * <h2>Zero-Allocation Tracing</h2>
 * <p>Both chain IDs and call IDs are primitive {@code long} values generated by
 * {@link java.util.concurrent.atomic.AtomicLong} counters — chain IDs come from a
 * global counter, call IDs from a per-chain counter, both centralised in
 * {@link eu.inqudium.core.pipeline.PipelineIds}. No {@link java.util.UUID} objects,
 * no strings, no boxing on the hot path.</p>
 *
 * @since 0.4.0
 */
package eu.inqudium.core.pipeline;
