/**
 * Unified wrapper pipeline for cross-cutting concerns around functional interfaces.
 *
 * <p>This package provides a decorator-based pipeline that wraps standard Java functional
 * interfaces ({@link java.lang.Runnable}, {@link java.util.function.Supplier},
 * {@link java.util.concurrent.Callable}, {@link java.util.function.Function}) and
 * AOP proxy executions ({@link eu.inqudium.core.pipeline.ProxyExecution}) in a chain
 * of layers with <strong>around-semantics</strong>.</p>
 *
 * <h2>Architecture Overview</h2>
 * <pre>{@code
 *                  LayerAction<A, R>                   // around-advice (functional interface)
 *                  ┌────────┴────────┐
 *                  │                 │
 *          InqExecutor<A, R>   InqDecorator<A, R>      // + executeXxx()  │  + InqElement (name, type, events)
 *                              ┌────┤                  //                 │  + decorateXxx()
 *                              │    │
 *                       Bulkhead<A,R>  (other decorators...)              // concrete resilience elements
 *                              │
 *               ┌──────────────┼──────────────┐
 *               │              │              │
 *              Wrapper<S>   BaseWrapper    InternalExecutor<A, R>         // chain infrastructure
 *                           ┌──┴──┐
 *          RunnableWrapper  SupplierWrapper  CallableWrapper  FunctionWrapper  JoinPointWrapper
 * }</pre>
 *
 * <h2>Core Concepts</h2>
 *
 * <h3>LayerAction — Around-Advice</h3>
 * <p>A {@link eu.inqudium.core.pipeline.LayerAction} is a functional interface that receives
 * the chain ID, call ID, argument, and a reference to the next step. It decides when,
 * whether, and how to invoke the next step — enabling pre-processing, post-processing,
 * exception handling, caching, retries, and conditional execution.</p>
 *
 * <h3>InqExecutor — Immediate Execution</h3>
 * <p>{@link eu.inqudium.core.pipeline.InqExecutor} extends {@code LayerAction} with
 * {@code executeXxx()} methods that invoke the around-advice immediately without creating
 * wrapper objects. One {@link eu.inqudium.core.pipeline.InternalExecutor} lambda per call,
 * two primitive IDs — zero other allocation on the hot path.</p>
 *
 * <h3>InqDecorator — Self-Describing Pipeline Element</h3>
 * <p>{@link eu.inqudium.core.pipeline.Decorator InqDecorator} combines
 * {@link eu.inqudium.core.element.InqElement} (name, type, event publisher) with
 * {@code LayerAction} (around-advice) and adds {@code decorateXxx()} factory methods
 * that create reusable wrapper objects for deferred execution. {@code InqDecorator} and
 * {@code InqExecutor} are independent siblings — both extend {@code LayerAction}, but
 * neither depends on the other.</p>
 *
 * <h3>Wrapper Chain — Immutable Layer Stack</h3>
 * <p>{@link eu.inqudium.core.pipeline.BaseWrapper} links layers into an immutable chain.
 * Each wrapper holds a pre-resolved {@code nextStep} reference (no runtime
 * {@code instanceof} checks), a shared per-chain call ID counter
 * ({@link java.util.concurrent.atomic.AtomicLong}), and a chain ID (primitive
 * {@code long}). The chain is safe to share across threads without synchronization.</p>
 *
 * <h2>Two Execution Modes</h2>
 *
 * <table>
 *   <tr><th></th><th>{@code decorateXxx()}</th><th>{@code executeXxx()}</th></tr>
 *   <tr><td><b>Timing</b></td><td>Deferred — returns a wrapper</td><td>Immediate — returns the result</td></tr>
 *   <tr><td><b>Allocation</b></td><td>Wrapper + core lambda + nextStep</td><td>One InternalExecutor lambda only</td></tr>
 *   <tr><td><b>Reusable</b></td><td>Yes — call the wrapper repeatedly</td><td>No — one-shot execution</td></tr>
 * </table>
 *
 * <h2>Usage Examples</h2>
 *
 * <h3>Immediate execution (no wrapper objects)</h3>
 * <pre>{@code
 * Bulkhead<Void, String> bulkhead = Bulkhead.of(config);
 * String result = bulkhead.executeSupplier(() -> callApi());
 * }</pre>
 *
 * <h3>Deferred execution (reusable wrapper)</h3>
 * <pre>{@code
 * Supplier<String> protected = bulkhead.decorateSupplier(() -> callApi());
 * protected.get();  // can call multiple times
 * }</pre>
 *
 * <h3>Composing multiple decorators</h3>
 * <pre>{@code
 * Supplier<String> resilient = retry.decorateSupplier(
 *     bulkhead.decorateSupplier(() -> callApi())
 * );
 * }</pre>
 *
 * <h3>Custom LayerAction lambda</h3>
 * <pre>{@code
 * new SupplierWrapper<>("timing", delegate, (chainId, callId, arg, next) -> {
 *     long start = System.nanoTime();
 *     String result = next.execute(chainId, callId, arg);
 *     metrics.record(System.nanoTime() - start);
 *     return result;
 * });
 * }</pre>
 *
 * <h2>Zero-Allocation Tracing</h2>
 * <p>Both chain IDs and call IDs are primitive {@code long} values generated by
 * {@link java.util.concurrent.atomic.AtomicLong} counters — one global counter for
 * chain IDs, one shared counter per chain for call IDs. No {@link java.util.UUID}
 * objects, no strings, no boxing on the hot path.</p>
 *
 * @since 0.4.0
 */
package eu.inqudium.core.pipeline;
