package eu.inqudium.core.pipeline;

import java.util.concurrent.atomic.AtomicLong;

import static eu.inqudium.core.pipeline.ChainIdGenerator.CHAIN_ID_COUNTER;

/**
 * ID generator for standalone (non-chained) executions.
 *
 * <p>When code needs chain-compatible IDs but is not running inside a wrapper
 * chain — for example, the {@code executeXxx()} methods on {@code InqExecutor},
 * test harnesses, or standalone utility methods — this class provides globally
 * unique IDs that are interoperable with the wrapper infrastructure.</p>
 *
 * <p>Chain IDs are drawn from the same global counter as
 * {@link ChainIdGenerator#CHAIN_ID_COUNTER}, ensuring no collisions with
 * IDs generated by wrapper chains. Call IDs use a separate static counter
 * specific to standalone executions.</p>
 *
 * <p>Both counters use {@link AtomicLong} for thread-safe, lock-free generation
 * — one CAS operation per ID, zero object allocation.</p>
 *
 * <p>This class is a stateless utility holder — it cannot be instantiated.</p>
 */
public final class StandaloneIdGenerator {

    /**
     * Standalone call-ID counter — separate from per-chain call-ID counters
     * in wrapper chains. Monotonically increasing, unique within the JVM.
     */
    private static final AtomicLong CALL_ID_COUNTER = new AtomicLong();

    /**
     * Prevent instantiation — this is a utility class.
     */
    private StandaloneIdGenerator() {
    }

    /**
     * Generates the next globally unique chain ID.
     *
     * <p>Uses the same global counter as wrapper chains, so the returned ID
     * will never collide with any chain ID generated by
     * {@link AbstractBaseWrapper}.</p>
     *
     * @return a new, unique chain ID
     */
    public static long nextChainId() {
        return CHAIN_ID_COUNTER.incrementAndGet();
    }

    /**
     * Generates the next globally unique standalone call ID.
     *
     * <p>Note: these IDs live in a separate counter space from per-chain
     * call IDs. They are useful for one-shot executions that don't belong
     * to a persistent wrapper chain.</p>
     *
     * @return a new, unique call ID
     */
    public static long nextCallId() {
        return CALL_ID_COUNTER.incrementAndGet();
    }
}
